agentName: alexa-demo
agentType: alexa-demo
title: 'Time to read a book'
metaDescription: 'Reading a book with the branching doc.'
introFilePath: 'src/install/alexa-demo/theStory/intro.mdx'
agentConfigFilePath: 'src/install/config/alexa-demo.yaml'
appInfo:
  - optionType: theStory
    label: 'Do you want to read something fun?'
    placeholder: 'Well since you asked...'
    options:
      - value: 'ch1'
        displayName: 'Something fun sounds great. Thanks!'
      - value: 'dontwant'
        displayName: 'Absolutely not.'

steps:
  - filePath: 'src/install/alexa-demo/nondefault-files/appInfo.mdx'
  - filePath: 'src/install/alexa-demo/theStory/default.mdx'
    overrides:
      - filePath: 'src/install/alexa-demo/theStory/ch1.mdx'
        selectedOptions:
          - optionType: theStory
            options:
              - value: 'ch1'
      - filePath: 'src/install/alexa-demo/theStory/dontwant.mdx'
        selectedOptions:
          - optionType: theStory
            options:
              - value: 'dontwant'
  - filePath: 'src/install/alexa-demo/theStory/tabs.mdx'
    overrides:
        - skip: true
          selectedOptions:
            - optionType: theStory
              options:
                - value: 'dontwant'
whatsNextFilePath: 'src/install/alexa-demo/nondefault-files/whatsNext.mdx'