agentName: alexa-demo
agentType: alexa-demo
title: 'Time to read a book'
metaDescription: 'Reading a book with the branching doc.'
introFilePath: 'src/install/alexa-demo/theStory/intro.mdx'
agentConfigFilePath: 'src/install/config/alexa-demo.yaml'
appInfo:
  - optionType: theStory
    label: 'Do you want to read something fun?'
    placeholder: 'Well since you asked...'
    options:
      - value: 'ch1'
        displayName: 'Absolutely!'
      - value: 'dontwant'
        displayName: 'Absolutely not.'
  - optionType: randompics
    label: 'Pick one for a picture, idk'
    placeholder: 'This doesnt matter.'
    options: 
      - value: 'beyork'
        displayName: 'Beyork'
        logo: 'beyork'
      - value: 'bsph'
        displayName: 'Two friends'
        logo: 'bsph'
      - value: 'rhobh'
        displayName: 'Camille'
        logo: 'rhobh'
steps:
  - filePath: 'src/install/alexa-demo/nondefault-files/appInfo.mdx'
  - filePath: 'src/install/alexa-demo/theStory/default.mdx'
    overrides:
      - filePath: 'src/install/alexa-demo/theStory/ch1.mdx'
        selectedOptions:
          - optionType: theStory
            options:
              - value: 'ch1'
      - filePath: 'src/install/alexa-demo/theStory/dontwant.mdx'
        selectedOptions:
          - optionType: theStory
            options:
              - value: 'dontwant'
  - filePath: 'src/install/alexa-demo/theStory/tabs.mdx'
    overrides:
        - skip: true
          selectedOptions:
            - optionType: theStory
              options:
                - value: 'dontwant'
  - filePath: 'src/install/alexa-demo/randompics/default.mdx'
    overrides:
        - skip: true
          selectedOptions:
            - optionType: theStory
              options:
                - value: 'dontwant'
        - filePath: 'src/install/alexa-demo/randompics/bsph.mdx'
          selectedOptions:
            - optionType: theStory
              options:
                - value: 'ch1'
            - optionType: randompics
              options:
                - value: 'bsph'
        - filePath: 'src/install/alexa-demo/randompics/beyork.mdx'
          selectedOptions:
            - optionType: theStory
              options:
              - value: 'ch1'
            - optionType: randompics
              options: 
                - value: 'beyork'
        - filePath: 'src/install/alexa-demo/randompics/rhobh.mdx'
          selectedOptions:
            - optionType: theStory
              options: 
                - value: 'ch1'
            - optionType: randompics
              options:
                - value: 'rhobh'
whatsNextFilePath: 'src/install/alexa-demo/nondefault-files/whatsNext.mdx'