agentName: alexa-demo
agentType: APM
title: 'My easy branching doc'
metaDescription: "A branching doc for seeing Spot's fate."
introFilePath: 'src/install/alexa-demo/idgi/set-the-stage.mdx'
agentConfigFilePath: 'src/install/alexa-demo/idgi/agentConfig.mdx'
appInfo: 
  - optionType: theStory
    label: 'Messing around'
    placeholder: 'Choose how you interact with Spot'
    options: 
      - value: 'cheerhimon'
        displayName: 'Tell Spot he rules'
      - value: 'bemean'
        displayName: 'Shame spot'

steps:
  - filePath: 'src/install/alexa-demo/idgi/appInfo.mdx' 
  - filePath: 'src/install/alexa-demo/theStory/default.mdx'
    overrides: 
      - filePath: 'src/install/alexa-demo/theStory/cheerhimon.mdx'
        selectedOptions: 
          - optionType: theStory
            options: 
              - value: 'cheerhimon'
      - filePath: 'src/install/alexa-demo/theStory/bemean.mdx'
        selectedOptions: 
          - optionType: theStory
            options: 
              - value: 'bemean'
whatsNextFilePath: 'src/install/alexa-demo/idgi/whatsNext.mdx'