agentName: alexa-demo
agentType: APM
title: 'See Spot Run'
metaDescription: "A branching doc for seeing Spot's fate."
introFilePath: 'src/install/alexa-demo/idgi/set-the-stage.mdx'
agentConfigFilePath: 'src/install/alexa-demo/idgi/seeSpotRun.mdx'
appInfo: 
  - optionType: theStory
    label: 'See Spot run'
    placeholder: 'Choose how you interact with Spot'
    options: 
      - value: 'cheerhimon'
        displayName: 'Tell Spot to run'
      - value: 'bemean'
        displayName: 'Shame spot'
steps:
  - filePath: 'src/install/alexa-demo/idgi/seeSpotRun.mdx'
  - filePath: 'src/install/alexa-demo/idgi/agentConfig.mdx'
    overrides:
      - filePath: 'src/install/alexa-demo/theStory/cheerhimon.mdx'
        selectedOptions:
          - optionType: theStory
            options:
            - value: cheerhimon
  - filePath: 'src/install/alexa-demo/idgi/wheredSpotGo.mdx'
    overrides:
      - skip: true
        selectedOptions:
          - optionType: theStory
            options:
              - value: 'beMean'
  - filePath: 'src/install/alexa-demo/idgi/ohSpotNo.mdx'
whatsNextFilePath: 'src/install/java/whatsNext.mdx'