agentName: alexa-demo
agentType: APM
title: 'My easy branching doc'
metaDescription: "A branching doc for seeing Spot's fate."
introFilePath: 'src/install/alexa-demo/idgi/set-the-stage.mdx'
agentConfigFilePath: 'src/install/alexa-demo/idgi/agentConfig.mdx'
appInfo: 
  - optionType: theStory
    label: 'Read Spot a story'
    placeholder: 'Choose how you interact with Spot'
    options: 
      - value: 'cheerhimon'
        displayName: 'Tell Spot he rules'
      - value: 'bemean'
        displayName: 'Shame spot'
  - optionType: theStory2
    label: Neither Austen nor Dostoevsky, but a secret third thing...
    placeholder: Experimenting with what this Does...tovsky
    options:
      - value: 'air'
        displayName: Give Spot some air...
      - value: 'odyssey'
        displayName: Let Spot go on a journey...

steps:
  - filePath: 'src/install/alexa-demo/idgi/appInfo.mdx' 
  - filePath: 'src/install/alexa-demo/theStory/default.mdx'
    overrides: 
      - filePath: 'src/install/alexa-demo/theStory/cheerhimon.mdx'
        selectedOptions: 
          - optionType: theStory
            options: 
              - value: 'cheerhimon'
      - filePath: 'src/install/alexa-demo/theStory/bemean.mdx'
        selectedOptions: 
          - optionType: theStory
            options: 
              - value: 'bemean'
  - filePath: 'src/install/alexa-demo/theStory2/default.mdx'
  - filePath: 'src/install/alexa-demo/theStory2/air.mdx'
    overrides:
        selectedOptions: 
          - optionType: theStory2
            options:
            - value: 'air'
whatsNextFilePath: 'src/install/alexa-demo/idgi/whatsNext.mdx'