agentName: kubernetes
agentType: infrastructure
title: 'Install the New Relic integration for Kubernetes'
metaDescription: 'Here are several ways to install the New Relic integration for Kubernetes'
introFilePath: 'src/install/kubernetes/kubernetes-install-intro.mdx'
redirects:
  - /docs/integrations/kubernetes-integration/installation/install-fargate-integration
  - /docs/kubernetes-pixie/kubernetes-integration/installation/install-fargate-integration
  - /docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/install-fargate-integration

  - /docs/integrations/kubernetes-integration/installation/install-kubernetes-integration-windows
  - /docs/kubernetes-pixie/kubernetes-integration/installation/install-kubernetes-integration-windows

  - /docs/integrations/kubernetes-integration/installation/install-kubernetes-integration-using-helm
  - /docs/kubernetes-pixie/kubernetes-integration/installation/install-kubernetes-integration-using-helm


# -----------------------------------------------------------------
# Define the categories for each type of question you'll be asking:
# -----------------------------------------------------------------
appInfo:

# Create the selection options for Microsoft Windows:
  - optionType: using-windows
    label: ''
    placeholder: 'Make a selection:'
    options:
      - value: 'windows-no'
        displayName: 'No'
      - value: 'windows-yes'
        displayName: 'Yes'

# Create the selection options for Fargate:
  - optionType: using-fargate
    label: ''
    placeholder: 'Make a selection:'
    options:
      - value: 'fargate-no'
        displayName: 'No'
      - value: 'fargate-yes'
        displayName: 'Yes'

# Create the selection options for all the other environment options:
  - optionType: additional-environments
    label: ''
    placeholder: 'Choose one:'
    options:
      - value: 'eks'
        displayName: 'Amazon EKS/EKS Anywhere'
      - value: 'aks'
        displayName: 'Azure Kubernetes Servcie (AKS)'
      - value: 'gke'
        displayName: 'Google Kubernetes Engine'
      - value: 'openshift'
        displayName: 'OpenShift container platform'
      - value: 'pivotal'
        displayName: 'Pivotal Container Services (PKS/VMware Tanzu)'

# Create the selection option about whether to choose manual or automatic installation:
  - optionType: manual-or-cli
    label: ''
    placeholder: 'Make a selection'
    options:
      - value: 'cli'
        displayName: 'Guided installation'
      - value: 'manual'
        displayName: 'Manual'


# ----------------------------------------------------
# Ask the user four questions about their environment:
# ----------------------------------------------------

steps:

# Question 1: Ask the user if their cluster runs in Windows:
  - filePath: 'src/install/kubernetes/kubernetes-ask-windows.mdx'

# Question 2: Ask the user if their cluster is running with Fargate:
  - filePath: 'src/install/kubernetes/kubernetes-ask-fargate.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: using-windows
            options:
              - value: 'windows-no'


# Question 3: Ask the user if they are using any of these environments:
  - filePath: 'src/install/kubernetes/kubernetes-ask-other-environments.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: using-windows
            options:
              - value: 'windows-no'
          # Apply AND logic: docker-yes AND non-web-no
          - optionType: using-fargate
            options:
              - value: 'fargate-no'

# Question 4: Ask the user if they would like to use the guided installation or
# do a manual Helm setup:
  - filePath: 'src/install/kubernetes/kubernetes-ask-manual-or-cli.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: using-windows
            options:
              - value: 'windows-no'
          # Apply AND logic: docker-yes AND non-web-no
          - optionType: using-fargate
            options:
              - value: 'fargate-no'
          # Apply AND logic: all of the above plus one of the following:
          - optionType: additional-environments
            options:
              - value: 'eks'
              - value: 'aks'
              - value: 'gke'
              - value: 'openshift'
              - value: 'pivotal'

# --------------------------------------------------------------------
# Display steps with the Kubernetes content based on the user's responses:
# --------------------------------------------------------------------

# Display Windows installation information
  - filePath: 'src/install/kubernetes/kubernetes-install-windows.mdx'
    overrides:
      # Display this only if windows-yes
      - isConditionalStep: true
        selectedOptions:
          - optionType: using-windows
            options:
              - value: 'windows-yes'

# Display Fargate installation information
  - filePath: 'src/install/kubernetes/kubernetes-install-fargate.mdx'
    overrides:
      # Display this only if windows-no and fargate-yes
      - isConditionalStep: true
        selectedOptions:
          - optionType: using-windows
            options:
              - value: 'windows-no'
          #Apply AND logic: windows-no AND fargate-yes
          - optionType: using-fargate
            options:
              - value: 'fargate-yes'

# Display the initial OpenShift instructions
  - filePath: 'src/install/kubernetes/environment-specific-setups/kubernetes-openshift-1.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: using-windows
            options:
              - value: 'windows-no'
            #Apply AND logic: windows-no AND fargate-no
          - optionType: using-fargate
            options:
              - value: 'fargate-no'
            # Apply AND logic: windows-no AND fargate-no AND pivotal
          - optionType: additional-environments
            options:
              - value: 'openshift'

# Display guided installation for OpenShift if customer selected that:
  - filePath: 'src/install/kubernetes/environment-specific-setups/kubernetes-guided-install.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: using-windows
            options:
              - value: 'windows-no'
            #Apply AND logic: windows-no AND fargate-no
          - optionType: using-fargate
            options:
              - value: 'fargate-no'
            # Apply AND logic: windows-no AND fargate-no AND pivotal AND manual-yes
          - optionType: manual-or-cli
            options:
              -value: 'cli'
            # Apply AND logic: windows-no AND fargate-no AND pivotal
          - optionType: additional-environments
            options:
              - value: 'openshift'

# Display manual Helm installation for OpenShift if customer selected that:
  - filePath: 'src/install/kubernetes/kubernetes-install-helm.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: using-windows
            options:
              - value: 'windows-no'
            #Apply AND logic: windows-no AND fargate-no
          - optionType: using-fargate
            options:
              - value: 'fargate-no'
            # Apply AND logic: windows-no AND fargate-no AND pivotal
          - optionType: additional-environments
            options:
              - value: 'openshift'
            # Apply AND logic: windows-no AND fargate-no AND pivotal AND manual-yes
          - optionType: manual-or-cli
            options:
              -value: 'manual'

# Display the final steps for OpenShift, if the user had selected that:
  - filePath: 'src/install/kubernetes/environment-specific-setups/kubernetes-openshift-1.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: using-windows
            options:
              - value: 'windows-no'
            #Apply AND logic: windows-no AND fargate-no
          - optionType: using-fargate
            options:
              - value: 'fargate-no'
            # Apply AND logic: windows-no AND fargate-no AND pivotal
          - optionType: additional-environments
            options:
              - value: 'openshift'

# Tell users what their next options are:
whatsNextFilePath: 'src/install/python/python-agent-whats-next.mdx'