agentName: kubernetes
agentType: infrastructure
title: 'Install the New Relic integration for Kubernetes'
metaDescription: 'Here are several ways to install the New Relic integration for Kubernetes'
introFilePath: 'src/install/kubernetes/python-agent-intro.mdx'
redirects:
  - /docs/integrations/kubernetes-integration/installation/install-fargate-integration
  - /docs/kubernetes-pixie/kubernetes-integration/installation/install-fargate-integration
  - /docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/install-fargate-integration

  - /docs/integrations/kubernetes-integration/installation/install-kubernetes-integration-windows
  - /docs/kubernetes-pixie/kubernetes-integration/installation/install-kubernetes-integration-windows

# -----------------------------------------------------------------
# Define the categories for each type of question you'll be asking:
# -----------------------------------------------------------------
appInfo:

  - optionType: using-windows
    label: ''
    placeholder: 'Make a selection:'
    options:
      - value: 'windows-no'
        displayName: 'No'
      - value: 'windows-yes'
        displayName: 'Yes'

  - optionType: using-fargate
    label: ''
    placeholder: 'Make a selection:'
    options:
      - value: 'fargate-no'
        displayName: 'No'
      - value: 'fargate-yes'
        displayName: 'Yes'

  - optionType: additional-environments
    label: ''
    placeholder: 'Choose one:'
    options:
      - value: 'eks'
        displayName: 'Amazon EKS/EKS Anywhere'
      - value: 'aks'
        displayName: 'Azure Kubernetes Servcie (AKS)'
      - value: 'gke'
        displayName: 'Google Kubernetes Engine'
      - value: 'pivotal'
        displayName: 'Pivotal Container Services (PKS/VMware Tanzu)'

  - optionType: manual-or-cli
    label: ''
    placeholder: 'Make a selection'
    options:
      - value: 'manual-yes'
        displayName: 'Yes'
      - value: 'manual-no'
        displayName: 'No'

# ----------------------------------------------------
# Ask the user four questions about their environment:
# ----------------------------------------------------

steps:

# Question 1: Ask the user if their cluster runs in Windows:
  - filePath: 'src/install/kubernetes/kubernetes-ask-windows.mdx'

# Question 2: Ask the user if their cluster is running with Fargate:
  - filePath: 'src/install/kubernetes/kubernetes-ask-fargate.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: python-non-web
            options:
              - value: 'non-web-no'

# Question 3: Ask the user if they are using any of these environments:
  - filePath: 'src/install/kubernetes/kubernetes-ask-other-environments.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: using-windows
            options:
              - value: 'windows-no'
          # Apply AND logic: docker-yes AND non-web-no

          - optionType: using-fargate
            options:
              - value: 'fargate-no'

# Question 4: Ask the user if they would like to use the guided installation or
# do a manual Helm setup:
  - filePath: 'src/install/kubernetes/kubernetes-ask-ask-manual-or-cli.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: using-windows
            options:
              - value: 'windows-no'
          # Apply AND logic: docker-yes AND non-web-no

          - optionType: using-fargate
            options:
              - value: 'fargate-no'

# --------------------------------------------------------------------
# Display steps with the Python content based on the user's responses:
# --------------------------------------------------------------------

# Display the download information
  - filePath: 'src/install/python/python-agent-download.mdx'
    overrides:
      # First, display this for Docker yes/no plus any framework or server
      - isConditionalStep: true
        selectedOptions:
          # Apply OR logic: If docker-yes OR docker-no
          - optionType: python-docker
            options:
              - value: 'docker-yes'
              - value: 'docker-no'
          # Apply AND logic: docker-yes AND a framework AND a server
          - optionType: python-framework
            options:
              - value: 'cherrypy'
              - value: 'fastapi'
              - value: 'paste'
              - value: 'scgi'
              - value: 'starlette'
              - value: 'web2py'
              - value: 'unsupported-asgi-framework'
              - value: 'unsupported-wsgi-framework'
          # Add another AND logic:
          - optionType: python-server
            options:
              - value: 'ajp'
              - value: 'daphne'
              - value: 'fastcgi'
              - value: 'gunicorn'
              - value: 'hypercorn'
              - value: 'mod-wsgi-express'
              - value: 'tornado'
              - value: 'uvicorn'
              - value: 'uwsgi'
              - value: 'waitress'
      # Second, apply OR logic: display this if non-web = yes
      - isConditionalStep: true
        selectedOptions:
          - optionType: python-non-web
            options:
              - value: 'non-web-yes'

# Display the license information
  - filePath: 'src/install/python/python-agent-license.mdx'
    overrides:
      # First, display this for Docker yes/no plus any framework or server
      - isConditionalStep: true
        selectedOptions:
          # Apply OR logic: If docker-yes OR docker-no
          - optionType: python-docker
            options:
              - value: 'docker-yes'
              - value: 'docker-no'
          # Apply AND logic: docker-yes AND a framework AND a server
          - optionType: python-framework
            options:
              - value: 'cherrypy'
              - value: 'fastapi'
              - value: 'paste'
              - value: 'scgi'
              - value: 'starlette'
              - value: 'web2py'
              - value: 'unsupported-asgi-framework'
              - value: 'unsupported-wsgi-framework'
          # Add another AND logic:
          - optionType: python-server
            options:
              - value: 'ajp'
              - value: 'daphne'
              - value: 'fastcgi'
              - value: 'gunicorn'
              - value: 'hypercorn'
              - value: 'mod-wsgi-express'
              - value: 'tornado'
              - value: 'uvicorn'
              - value: 'uwsgi'
              - value: 'waitress'
      # Second, apply OR logic: display this if non-web = yes
      - isConditionalStep: true
        selectedOptions:
          - optionType: python-non-web
            options:
              - value: 'non-web-yes'

# Display the configuration information
  - filePath: 'src/install/python/python-agent-create-config-file.mdx'
    overrides:
      # First, display this for Docker yes/no plus any framework or server
      - isConditionalStep: true
        selectedOptions:
          # Apply OR logic: If docker-yes OR docker-no
          - optionType: python-docker
            options:
              - value: 'docker-yes'
              - value: 'docker-no'
          # Apply AND logic: docker-yes AND a framework AND a server
          - optionType: python-framework
            options:
              - value: 'cherrypy'
              - value: 'fastapi'
              - value: 'paste'
              - value: 'scgi'
              - value: 'starlette'
              - value: 'web2py'
              - value: 'unsupported-asgi-framework'
              - value: 'unsupported-wsgi-framework'
          # Add another AND logic:
          - optionType: python-server
            options:
              - value: 'ajp'
              - value: 'daphne'
              - value: 'fastcgi'
              - value: 'gunicorn'
              - value: 'hypercorn'
              - value: 'mod-wsgi-express'
              - value: 'tornado'
              - value: 'uvicorn'
              - value: 'uwsgi'
              - value: 'waitress'
      # Second, apply OR logic: display this if non-web = yes
      - isConditionalStep: true
        selectedOptions:
          - optionType: python-non-web
            options:
              - value: 'non-web-yes'

# Display the non-web app information:
  - filePath: 'src/install/python/python-agent-non-web-apps.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: python-non-web
            options:
              - value: 'non-web-yes'

# Display the Docker information:
  - filePath: 'src/install/python/python-agent-uvicorn-docker.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: python-non-web
            options:
              - value: 'non-web-no'
          # Apply AND logic:
          - optionType: python-docker
            options:
              - value: 'docker-yes'
          # Apply AND logic:
          - optionType: python-framework
            options:
              - value: 'cherrypy'
              - value: 'fastapi'
              - value: 'paste'
              - value: 'scgi'
              - value: 'starlette'
              - value: 'web2py'
              - value: 'unsupported-asgi-framework'
              - value: 'unsupported-wsgi-framework'
          # Apply AND logic:
          - optionType: python-server
            options:
              - value: 'ajp'
              - value: 'daphne'
              - value: 'fastcgi'
              - value: 'gunicorn'
              - value: 'hypercorn'
              - value: 'mod-wsgi-express'
              - value: 'tornado'
              - value: 'uvicorn'
              - value: 'uwsgi'
              - value: 'waitress'

# ------------------------------
# DISPLAY FRAMEWORK INFORMATION
# ------------------------------

# Display the CherryPy framework information:
  - filePath: 'src/install/python/python-frameworks/python-agent-cherrypy.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: python-framework
            options:
              - value: 'cherrypy'
          - optionType: python-server
            options:
              - value: 'ajp'
              - value: 'daphne'
              - value: 'fastcgi'
              - value: 'gunicorn'
              - value: 'hypercorn'
              - value: 'mod-wsgi-express'
              - value: 'tornado'
              - value: 'uvicorn'
              - value: 'uwsgi'
              - value: 'waitress'

# Display the FastAPI framework information:
  - filePath: 'src/install/python/python-frameworks/python-agent-fastapi.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: python-framework
            options:
              - value: 'fastapi'
          - optionType: python-server
            options:
              - value: 'ajp'
              - value: 'daphne'
              - value: 'fastcgi'
              - value: 'gunicorn'
              - value: 'hypercorn'
              - value: 'mod-wsgi-express'
              - value: 'tornado'
              - value: 'uvicorn'
              - value: 'uwsgi'
              - value: 'waitress'

# Display the Paste framework information:
  - filePath: 'src/install/python/python-frameworks/python-agent-paste.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: python-framework
            options:
              - value: 'paste'
          - optionType: python-server
            options:
              - value: 'ajp'
              - value: 'daphne'
              - value: 'fastcgi'
              - value: 'gunicorn'
              - value: 'hypercorn'
              - value: 'mod-wsgi-express'
              - value: 'tornado'
              - value: 'uvicorn'
              - value: 'uwsgi'
              - value: 'waitress'

# Display the SCGI framework information:
  - filePath: 'src/install/python/python-frameworks/python-agent-scgi.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: python-framework
            options:
              - value: 'scgi'
          - optionType: python-server
            options:
              - value: 'ajp'
              - value: 'daphne'
              - value: 'fastcgi'
              - value: 'gunicorn'
              - value: 'hypercorn'
              - value: 'mod-wsgi-express'
              - value: 'tornado'
              - value: 'uvicorn'
              - value: 'uwsgi'
              - value: 'waitress'

# Display the Starlette framework information:
  - filePath: 'src/install/python/python-frameworks/python-agent-starlette.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: python-framework
            options:
              - value: 'starlette'
          - optionType: python-server
            options:
              - value: 'ajp'
              - value: 'daphne'
              - value: 'fastcgi'
              - value: 'gunicorn'
              - value: 'hypercorn'
              - value: 'mod-wsgi-express'
              - value: 'tornado'
              - value: 'uvicorn'
              - value: 'uwsgi'
              - value: 'waitress'

# Display the Web2Py framework information:
  - filePath: 'src/install/python/python-frameworks/python-agent-web2py.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: python-framework
            options:
              - value: 'web2py'
          - optionType: python-server
            options:
              - value: 'ajp'
              - value: 'daphne'
              - value: 'fastcgi'
              - value: 'gunicorn'
              - value: 'hypercorn'
              - value: 'mod-wsgi-express'
              - value: 'tornado'
              - value: 'uvicorn'
              - value: 'uwsgi'
              - value: 'waitress'

# Display the unsupported ASGI framework information:
  - filePath: 'src/install/python/python-frameworks/python-agent-unsupported-asgi-frameworks.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: python-framework
            options:
              - value: 'unsupported-asgi-framework'
          - optionType: python-server
            options:
              - value: 'ajp'
              - value: 'daphne'
              - value: 'fastcgi'
              - value: 'gunicorn'
              - value: 'hypercorn'
              - value: 'mod-wsgi-express'
              - value: 'tornado'
              - value: 'uvicorn'
              - value: 'uwsgi'
              - value: 'waitress'

# Display the unsupported WSGI framework information:
  - filePath: 'src/install/python/python-frameworks/python-agent-unsupported-wsgi-frameworks.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: python-framework
            options:
              - value: 'unsupported-wsgi-framework'
          - optionType: python-server
            options:
              - value: 'ajp'
              - value: 'daphne'
              - value: 'fastcgi'
              - value: 'gunicorn'
              - value: 'hypercorn'
              - value: 'mod-wsgi-express'
              - value: 'tornado'
              - value: 'uvicorn'
              - value: 'uwsgi'
              - value: 'waitress'

# ------------------------------
# DISPLAY SERVER INFORMATION
# ------------------------------

# Display AJP WSGI server information:
  - filePath: 'src/install/python/python-servers/python-agent-ajp-wsgi.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: python-server
            options:
              - value: 'ajp'

# Display Daphne server information:
  - filePath: 'src/install/python/python-servers/python-agent-daphne.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: python-server
            options:
              - value: 'daphne'

# Display the FastCGI adapter information:
  - filePath: 'src/install/python/python-servers/python-agent-fastcgi.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: python-server
            options:
              - value: 'fastcgi'

# Display Gunuicorn server information:
  - filePath: 'src/install/python/python-servers/python-agent-gunicorn.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: python-server
            options:
              - value: 'gunicorn'

# Display the Hypercorn server information:
  - filePath: 'src/install/python/python-servers/python-agent-hypercorn.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: python-server
            options:
              - value: 'hypercorn'

# Display the mod-wsgi-express server information:
  - filePath: 'src/install/python/python-servers/python-agent-mod-wsgi-express.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: python-server
            options:
              - value: 'mod-wsgi-express'

# Display the Tornado server information:
  - filePath: 'src/install/python/python-servers/python-agent-tornado.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: python-server
            options:
              - value: 'tornado'

# Display the Uvicorn server information:
  - filePath: 'src/install/python/python-servers/python-agent-uvicorn.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: python-server
            options:
              - value: 'uvicorn'

# Display the UWSGI server information:
  - filePath: 'src/install/python/python-servers/python-agent-uwsgi.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: python-server
            options:
              - value: 'uwsgi'

# Display the waitress server information:
  - filePath: 'src/install/python/python-servers/python-agent-waitress.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: python-server
            options:
              - value: 'waitress'

# -------------------------------------
# WRAP IT UP!!
# -------------------------------------

# Tell users how to view their data:
  - filePath: 'src/install/python/python-agent-view-your-data.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: python-non-web
            options:
              - value: non-web-yes
      # Apply OR logic
      - isConditionalStep: true
        selectedOptions:
          - optionType: python-non-web
            options:
              - value: 'non-web-no'
          - optionType: python-docker
            options:
              - value: 'docker-yes'
              - value: 'docker-no'
          - optionType: python-framework
            options:
              - value: 'cherrypy'
              - value: 'fastapi'
              - value: 'paste'
              - value: 'scgi'
              - value: 'starlette'
              - value: 'web2py'
              - value: 'unsupported-asgi-framework'
              - value: 'unsupported-wsgi-framework'
          - optionType: python-server
            options:
              - value: 'ajp'
              - value: 'daphne'
              - value: 'fastcgi'
              - value: 'gunicorn'
              - value: 'hypercorn'
              - value: 'mod-wsgi-express'
              - value: 'tornado'
              - value: 'uvicorn'
              - value: 'uwsgi'
              - value: 'waitress'

# Tell users what their next options are:
whatsNextFilePath: 'src/install/python/python-agent-whats-next.mdx'