agentName: log-forwarding
agentType: Logging
title: 'Configure log forwarding'
metaDescription: 'Send logs to New Relic using a log forwarder.'
introFilePath: 'src/install/log-forwarding/intro.mdx'
appInfo:
  - optionType: forwarderOption
    label: ''
    placeholder: 'Choose a log forwarder'
    options:
      - value: 'infraAgent'
        displayName: 'Infrastructure agent (recommended)'
        logo: ''
      - value: 'awsLambdaCloudwatch'
        displayName: 'AWS Lambda Cloudwatch'
        icon: 'awsLambda'
steps:
  - filePath: 'src/install/log-forwarding/get-license-key.mdx'
  - filePath: 'src/install/log-forwarding/choose-forwarder.mdx'
  - filePath: 'src/install/log-forwarding/forwarder-options/aws-lambda-cloudwatch.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: forwarderOption
            options:
              - value: 'awsLambdaCloudwatch'    
  - filePath: 'src/install/log-forwarding/forwarder-options/infrastructure-agent.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: forwarderOption
            options:
              - value: 'infraAgent'
  - filePath: 'src/install/log-forwarding/view-data.mdx'
whatsNextFilePath: 'src/install/log-forwarding/whats-next.mdx'
