agentName: Log forwarding
agentType: Logging
title: 'Configure log forwarding'
metaDescription: 'Send logs to New Relic using a log forwarder.'
introFilePath: 'src/install/log-forwarding/intro.mdx'
agentConfigFilePath: 'src/install/log-forwarding/config/config.txt' //need to add
appInfo:
  - optionType: forwarderOption
    label: 'Choose a log forwarder'
    placeholder: 'Choose a log forwarder'
    options:
      - value: 'infraAgent'
        displayName: 'Infrastructure agent (recommended)'
        logo: '' //need to add
        recommendedGuided: true
      - value: 'AWS Lambda Cloudwatch'
        displayName: 'Second option'
        icon: 'awsLambda.svg'
steps:
  - filePath: 'src/install/log-forwarding/get-license-key.mdx'
  - filePath: 'src/install/log-forwarding/choose-forwarder.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: forwarderOption
            options:
              - value: 'infraAgent'
  - filePath: 'src/install/log-forwarding/configure-forwarder.mdx'
  - filePath: 'src/install/log-forwarding/view-data.mdx'
whatsNextFilePath: 'src/install/demo/whatsNext.mdx'
